/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package Lab1;
// gradle automatically added the above line which will mess things up in this lab.

// 19-20Spr Comp3111 Lab01Git by Kwok Wang Chi 20619962
public class Library {
	
	public static void main(String arg[]) {
		Library lib = new Library();
		if (lib.someLibraryMethod()) {
			System.out.println("When there is a fire, commit and push. =)");
		}
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
